#!/usr/bin/env osascript

tell application "iPhone Simulator"
    activate
end tell

delay 10

tell application "System Events"
    tell process "iPhone Simulator"
        tell menu bar 1
            tell menu bar item "Hardware"
                tell menu "Hardware"
                    click menu item "Rotate Right"
		    delay 15
                end tell
            end tell
        end tell
    end tell
end tell
